---
title: "Transmission of Genetic Information"
engine: knitr
format: 
  html: 
    self-contained: true
    css: ../custom.css
webr: 
  packages: ['ggplot2', 'dplyr']
filters: 
  - webr
---

```{r}
#| echo: false
#| message: false
#| warning: false

library(ggplot2)
library(dplyr)
```


## Overview


## Learning Objectives

- Calculate the probability of a particular gamete being produced from an individual, assuming independent assortment.
- Calculate the probability of a particular genotype in the offspring for 1-3 genes, given independent assortment and random fertilization between two individuals.
- Design genetic crosses to provide information about genes, alleles, and gene functions.
- Use a Chi-squared test to determine how well data from a genetic cross fits theoretical predictions.
- Explain how sample size is related to the certainty of estimates (CIs, Chi-squared test).


## Review of independent assortment

Leads to predictable probabilities


## Probability

Blood types (3 alleles + [co]dominance) and Rh factors are independent

Proportions as probabilities and proportions as probabilities


## What is a confidence interval?


## Confidence intervals for proportions

Effect of sample size on CIs


## Chi-squared test

Statistical test in reverse – significant test is a lack of fit


## Using a Chi-squared test

Days of birth

> What is your prediction?


## Case study: Detecting a recessive muscle mutation in mice

